version: '3.8'

services:
  sede:
    image: ghcr.io/metro-olografix/sede:dev
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./database:/app/database
    networks:
      - "internal-apps"
    env_file: backend.env

networks:
  internal-apps:
    external: true